### ISSUE TITLE
Cover image not full screen on Kobo Aura One

### ISSUE THREAD

**Issue by DARKFiB3R** [benchen71/epub-metadata-editor#56]
Also, Calibre states that 0000Cover.jpg is not in the manifest

Link to epub and jpg.. https://wormhole.app/GYvOm#kjXayBwkhvmAozP3bRsVWQ

I should try to find a better file host, as that link is only live for 24 hours :(

**Comment by benchen71** [comment]
No prob. I've downloaded the files.

Looking at your EPUB file I can see the problem. You have clearly used EPUB Metadata Editor to prioritise the cover file, and for some reason, the program didn't put the item into the manifest correctly. But I have no idea why. If you had a copy of the EPUB before prioritising I could perhaps do something?

In the mean time, I fixed the manifest error for you. Download this zip file and then change the .zip to .epub.
[Ender's Game - Orson Scott Card.zip](https://github.com/benchen71/epub-metadata-editor/files/6321585/Ender.s.Game.-.Orson.Scott.Card.zip)

**Comment by DARKFiB3R** [comment]
Thanks for your help. Unfortunetly, the issue is still there with your upload.

Previously I had been messing about with calibre and chose to prioritise the new cover file from EPUB Metadata Editor, to see if that would make it full screen. That is when I got the error message about the manifest.

This is the original epub... https://wormhole.app/gQKkL#fcQ4s8uC7-rB1j9Cqbm83g

Thanks again.

**Comment by benchen71** [comment]
The issue with a cover image not appearing full screen on an ereader is a different problem entirely, one that EPUB Metdata Editor does not fix. The reason why the image does not appear full screen is (I think) because it is a small image. The one in the original EPUB is only 480 x 736. The image in the edited EPUB (from your first post) is 639 x 1000. But the Kobo Aura One has a pixel size of 1404 x 1872.

The prioritising of the cover is a way of making sure that the cover image is the first image (by sort order) in the EPUB so that the operating system will use that image for the icon. However, I think there is a problem with the way EPUB Metadata Editor handled the prioritisation process with your EPUB file (putting the prioritised cover item outside the manifest), so I will investigate that issue further. But I can't do anything about the full screen image issue.
